#############################################################################
# Makefile for building: font
# Generated by qmake (2.01a) (Qt 4.7.2) on: ?? ????. 23 04:50:23 2011
# Project:  font.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile font.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		fontrender.cpp \
		fontview.cpp \
		imagepacker.cpp \
		imagecrop.cpp \
		guillotine.cpp \
		imagesort.cpp \
		maxrects.cpp moc_mainwindow.cpp \
		moc_fontrender.cpp \
		moc_fontview.cpp
OBJECTS       = main.o \
		mainwindow.o \
		fontrender.o \
		fontview.o \
		imagepacker.o \
		imagecrop.o \
		guillotine.o \
		imagesort.o \
		maxrects.o \
		moc_mainwindow.o \
		moc_fontrender.o \
		moc_fontview.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		font.pro
QMAKE_TARGET  = font
DESTDIR       = 
TARGET        = font

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: font.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile font.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile font.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/font1.0.0 || $(MKDIR) .tmp/font1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/font1.0.0/ && $(COPY_FILE) --parents mainwindow.h fontrender.h fontview.h imagepacker.h guillotine.h maxrects.h .tmp/font1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp fontrender.cpp fontview.cpp imagepacker.cpp imagecrop.cpp guillotine.cpp imagesort.cpp maxrects.cpp .tmp/font1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/font1.0.0/ && (cd `dirname .tmp/font1.0.0` && $(TAR) font1.0.0.tar font1.0.0 && $(COMPRESS) font1.0.0.tar) && $(MOVE) `dirname .tmp/font1.0.0`/font1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/font1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_fontrender.cpp moc_fontview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_fontrender.cpp moc_fontview.cpp
moc_mainwindow.cpp: fontrender.h \
		ui_mainwindow.h \
		fontview.h \
		imagepacker.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_fontrender.cpp: ui_mainwindow.h \
		fontview.h \
		imagepacker.h \
		fontrender.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fontrender.h -o moc_fontrender.cpp

moc_fontview.cpp: fontview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fontview.h -o moc_fontview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		fontview.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		fontrender.h \
		ui_mainwindow.h \
		fontview.h \
		imagepacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		fontrender.h \
		ui_mainwindow.h \
		fontview.h \
		imagepacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

fontrender.o: fontrender.cpp fontrender.h \
		ui_mainwindow.h \
		fontview.h \
		imagepacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontrender.o fontrender.cpp

fontview.o: fontview.cpp fontview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontview.o fontview.cpp

imagepacker.o: imagepacker.cpp imagepacker.h \
		guillotine.h \
		maxrects.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagepacker.o imagepacker.cpp

imagecrop.o: imagecrop.cpp imagepacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagecrop.o imagecrop.cpp

guillotine.o: guillotine.cpp guillotine.h \
		imagepacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guillotine.o guillotine.cpp

imagesort.o: imagesort.cpp imagepacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagesort.o imagesort.cpp

maxrects.o: maxrects.cpp maxrects.h \
		imagepacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxrects.o maxrects.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_fontrender.o: moc_fontrender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontrender.o moc_fontrender.cpp

moc_fontview.o: moc_fontview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontview.o moc_fontview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

